version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: judas_redis
    restart: unless-stopped
    ports:
      - "6379:6379"           # host → container
    command: >
      redis-server --appendonly yes --save 60 1000
    volumes:
      - ./data/redis:/data    # keeps data if the container restarts
